#JSON 超集
person:
  id: 2
  name: 张三
  hobby:
    - play
    - read
    - sleep
  family: [ father , mother ]
#  map:
#    k1: v1
#    k2: v2

  map:
    { k1: k1 , k2: k2}
  pet: { type: cat , name : Tom}
student:
  name: 张三

#spring:
#  profiles:
#    active: dev
server:
  port: 8081